# Generated by Django 5.1.7 on 2025-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movid', models.CharField(help_text='Employee ID', max_length=20)),
                ('movname', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('movtype', models.CharField(max_length=100)),
                ('movlength', models.FloatField()),
            ],
        ),
    ]
