# Generated by Django 5.1.7 on 2025-04-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_DB',
            fields=[
                ('Movie_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=20)),
                ('Rating', models.IntegerField()),
                ('Language', models.CharField(max_length=15)),
                ('Release_Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
